version: '3.1'

services:
  postgres_db:
    build: ./postgres/
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql

  cl-api:
    build: .
    depends_on:
      - postgres_db
    ports:
      - 8080:8080